### ISSUE TITLE
Emails after unsubscribing, and missing preferences

### ISSUE THREAD

**Issue by colemickens** [mozmeao/basket#1190]
>You're receiving this email because cole.mickens@determinate.systems has a Firefox account and is subscribed to Firefox Account Tips.

One, I never signed up for that.

Two, I've clicked unsubscribe at least once.

Three, that "Firefox Account Tips" does not even appear in the "Manage Communication Preferences" page.

I consider this spam, and it's kind of disappointing. Hopefully just a bug.

**Comment by pmac** [comment]
I'm told that the email(s) you received are part of an automatic set of messages that everyone gets when signing up for a new Firefox Account. I've confirmed that you are unsubscribed and should not receive any further emails. If you do please update here and we'll investigate further. I do think this is potentially a bug due to how we handle unsubscribes and how quickly our email partner recognizes the unsubscribe. We are working on improving that, but for now I can just apologize for the confusing experience. I'm glad you found this issue tracker and reported this to us. I assure you we don't want to email anyone who doesn't want it.

**Comment by colemickens** [comment]
Not to complain, but as another data point, since you confirmed it appears unsubscribed on your side...

I did receive another email from the same series "Superpower #4: See if your info has been leaked". Heh.

**Comment by pmac** [comment]
🤦 thanks for the update. I'll check with them again.

**Comment by pmac** [comment]
We've taken the extra step of adding you to the "suppression list" which should make it impossible for the system to send you a mail, even if it wants to. Thanks again for the update, and please let me know if this fails as we could have a much bigger issue.
