### ISSUE TITLE
Extra CTMS record created for FxA user

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#1466]
See [this diagram](https://gist.github.com/grahamalama/c4cb75fd6cc2e220e49ee630b3b6031b) for a flow chart of what is happening.

## What is currently happening

1. A user creates an FxA
2. User changes the primary email on their FxA
3. User clicks the link in the FxA UI to manage their email preferences
4. Basket gets that request and [attempts to look up the user by email address](https://github.com/mozmeao/basket/blob/fdede676203a90e92f85c0ee7845812ec8e7e8b4/basket/news/views.py#L169)
5. CTMS says there is no user with that email address because the user is in the system with their original email
6. Basket creates a new record in CTMS with the new email address 
7. Basket redirects the user to the email preferences page using the newly created CTMS entry data

## What should happen

For step 4 above, the first lookup that basket tries should be with the user's FxA ID. So we need to figure out if the FxA ID is part of the [data returned by FxA during the Oauth process](https://github.com/mozmeao/basket/blob/fdede676203a90e92f85c0ee7845812ec8e7e8b4/basket/news/views.py#L161).

**Comment by robhudson** [comment]
I verified that the `get_user_data` call fails to find the user record when the provided email is swapped with the new primary email. But adding in the fxa ID to the call returns the correct user record.

The draft PR (https://github.com/mozmeao/basket/pull/1469) gets the `uid` from the FxA call and uses it in the `get_user_data` call to find the correct record. I tested that this does reflect the `fxa_primary_email` change before and after updating the primary email. The CTMS `email` field remains the same -- the original email.

So the change should find the correct user record and redirect them to the pref center correctly since it would find the token.

This is all assuming that the `uid` returned from FxA is the `fxa_id` we pass to CTMS. It's hard to test the oauth flow from a console, so I'll test this on the basket dev server next chance I get to confirm the fix.
