### ISSUE TITLE
subscription services enhancements

### ISSUE THREAD

**Issue by metadave** [mozmeao/basket#147]
TODO

**Comment by blavine** [comment]
The Customer Operations (Subscription Services project team) is currently working on a tickets for Salesforce to identify the data elements that will be stored, the table or tables where this will be mapped to and any parameters that are needed for delivering this data.  The plan is to send the data from SubHub to an Amazon SQS queue and then for Basket to pick up those messages and send to Salesforce.  Therefore we need to have the details around the AWS SQS queue to utilize, any keys, the data layout, etc.  Once this is mapped out, this request is to have Paul M create the processes to read this additional data and deliver to Salesforce.

@pmac @metadave Can you please confirm if you need additional information in order to estimate the effort and timeline for this work? Thanks.

**Comment by pmac** [comment]
Hi @blavine. Thanks for providing this info. I think the main thing we need before we'll be able to provide a good estimate is the data model you mentioned (the fields and type of data to be sent to us), and where exactly it will be stored, i.e. will it it be in Salesforce CRM or Salesforce Marketing Cloud? Also the expected volume (or rate of delivery) of these data would be helpful.

**Comment by pmac** [comment]
I believe this is now done and soon to be in production on the SubHub side.
