### ISSUE TITLE
Updates to FxA Feed to SalesCloudcCRM 

### ISSUE THREAD

**Issue by andrewmozilla** [mozmeao/basket#405]
This request is related to the work that has already been done on the Basket side around turning on the feed for FxA Contacts to come into Salesforce CRM. 

UPDATES FROM LCM:
For Net Net New verified account holder records feeding into CRM:

- Bring over FxA ID
- Flip Double Opt In to True
- Flip Subscriber to True
- Flip Email Format to H
- Flip Firefox Account Tips Subscriber field to True
- Flip any other applicable subscription fields to True that were a part of their signup process (i.e. FxA subscription options upon signup: Knowledge is Power Subscription, New Product Testing Subscriber, Take Action for the Internet Subscription)
- Bring over FxA language and populate Newsletter Language (based on previously discussed & agreed upon mapping - one of our standard 9 locales or “Other”; I believe you wanted to capture the ACTUAL language from FxA in another new field too in case it was ever needed.)

**Comment by pmac** [comment]
What of this should happen if a user is being updated instead of created? I assume:

- Bring over FxA ID
- Ensure Double Opt In is True
- Ensure Subscriber is True
- Flip Firefox Account Tips Subscriber field to True
- Flip any other applicable subscription fields to True that were a part of their signup process (i.e. FxA subscription options upon signup: Knowledge is Power Subscription, New Product Testing Subscriber, Take Action for the Internet Subscription)
- Bring over FxA language and populate Newsletter Language (based on previously discussed & agreed upon mapping - one of our standard 9 locales or “Other”; I believe you wanted to capture the ACTUAL language from FxA in another new field too in case it was ever needed.) if they don't already have a language specified.

**Comment by pmac** [comment]
@andrewmozilla I've got a PR in for this that I think covers everything. Do you think it's good to go or should we have a quick meeting to be sure we're on the same page?

**Comment by andrewmozilla** [comment]
Adding a request for another attribute that LCM would like to have brought over with the insert or update call. They would like CREATED_DATE to be brought over which outlines when the FxA Account was created. I/we will need to create the field on the Contact record to accommodate.

**Comment by pmac** [comment]
This issue is already closed and fixed via a PR weeks ago. Would you mind opening a new issue for any new requests?

**Comment by pmac** [comment]
Actually we already have `FxA_Created_Date__c` (via [this issue](https://github.com/mozmeao/basket/issues/149#issuecomment-525018546)) on the contact and basket is already ready to handle it.
