### ISSUE TITLE
AMO <> Salesforce Expanded Integration Phase 1

### ISSUE THREAD

**Issue by mozbrandon** [mozmeao/basket#522]
Here's what's needed for phase 1 of the expanded amo integration. 

**Field Mapping:** https://docs.google.com/spreadsheets/d/1ejdszPXF7WIX284UTpXM9Fs2PonTRycGQwEtrkkRT2A/edit?usp=sharing

**Action/Outcome:** https://docs.google.com/document/d/1PIBgZmxbfI-LZlSkB0j4N3wUeJFb2v1JJos8QPHnNSk/edit?usp=sharing

Thank you!

**Comment by pmac** [comment]
@mozbrandon do you know how different this is from what was discussed the first time in #148 and the work done in #223 ?

**Comment by glogiotatidis** [comment]
Hi @mozbrandon a couple of questions:
 - `AMO_Recommended__c` is it implemented as Boolean or `Yes` / `No`?
 - `AMO_Account_Deleted__c` is it implemented as Boolean or `Yes` / `No`?

Also currently when a user is reported deleted by AMO we set `AMO_User__c` to `False`, do we still need this behavior?

**Comment by glogiotatidis** [comment]
More recent Spec https://addons-server.readthedocs.io/en/latest/topics/basket.html

**Comment by glogiotatidis** [comment]
After chatting with @diox we know that AMO notifies basket when
 - A user changes their email
 - A user deletes their account

There's no notification when a user adds a secondary email, since AMO knows nothing the secondary email residing on FxA side. Also a user must have an email, so there's no way they can remove their primary email.

@mozbrandon can you please help us understand what's requested here?  

Since AMO uses FxA I guess the email related information can be sent to Basket by FxA. Or maybe is it already handled @pmac?

**Comment by pmac** [comment]
We do get primary email change notifications from FxA but we just currently store those in another location and don't use them for SFDC contacts. There are a number of bugs filed about it due to us sending email to the old addresses, but it's not fixed yet. @mozbrandon tells me that they're not allowed to work on the FxA email change issue at the moment, so I think all we can do is handle the email change event from AMO.

**Comment by mozbrandon** [comment]
@glogiotatidis Caitlin and Jorge mentioned there being the following functionality in the AMO user interface for an end-user to:

- Add a secondary email to their AMO account
- Remove their primary email address from their AMO account.

The requirements we received and information gathered outlined capturing this data in Salesforce when these actions were performed. Please reach out to Caitlin and Jorge if this functionality does not exist in the AMO user interface as it will need to be added.

@pmac It is true that the business has not given us approval to work on FxA component and all that it entails.

**Comment by diox** [comment]
AMO doesn't know anything about the secondary email, it doesn't receive or store that information. The primary (and only) email can change though (via admins changing it, or via FxA notifying the user has changed their primary FxA email, which is why AMO uses). When that happens, we notify basket that the AMO user has had one of their properties changed, and the properties include the new email value.

**Comment by pmac** [comment]
Nice! We've had this email change issue with FxA for years now. If we could just solve that it sounds like we'd solve this as well.

**Comment by andrewmozilla** [comment]
@pmac Ill get a quick 30 mins down. I want to make sure we're on the same page with the AMO team and yourself. Ill stalk your cal.

**Comment by andrewmozilla** [comment]
Meeting for Mon but would like to try to keep this moving. 
@diox: 
- Is the "remove primary email" from their AMO account a workflow we still need to support? If so, does this mean that they are deleting their FxA Account or is that a separate action?
- Am I correct in understanding that we do not need to account for a secondary email of any kind?
- When someone updates their FxA Email address, you would like that passed through and updated on the CRM record correct? What do you want to happen if that person is also a donor on the MoFo side? Do you still want their email address updated? This is a shared CRM across Mozilla so we need to be explicit in our desired actions. 

cc @mozbrandon

**Comment by glogiotatidis** [comment]
> Hi @mozbrandon a couple of questions:
> 
>     * `AMO_Recommended__c` is it implemented as Boolean or `Yes` / `No`?
> 
>     * `AMO_Account_Deleted__c` is it implemented as Boolean or `Yes` / `No`?
> 
> 
> Also currently when a user is reported deleted by AMO we set `AMO_User__c` to `False`, do we still need this behavior?

Hi @mozbrandon. Do you want to answer the above so we move 2/4 requests fwd? Thanks!

**Comment by andrewmozilla** [comment]
Hi All. Capturing notes from our sync earlier today.

- AMO will now (not) be sending email address in the payload since it should be coming in already via the FxA feed. 
- AMO will now be sending FxA ID w the payload
- CRM team to add in field - FxA_Primary_Email__c to capture email address changes via the FxA feed. Work tracked here: https://github.com/mozmeao/basket/issues/532
- When a dev deletes their AMO account (independednt of deleting FxA account) "AMO Deleted" field will be updated (boolean) 
- CRM team to delete fields AMO secondary email and AMO primary fields as they are not needed. 

cc @mozbrandon

**Comment by mozbrandon** [comment]
> 
> 
> > Hi @mozbrandon a couple of questions:
> > ```
> > * `AMO_Recommended__c` is it implemented as Boolean or `Yes` / `No`?
> > 
> > * `AMO_Account_Deleted__c` is it implemented as Boolean or `Yes` / `No`?
> > ```
> > 
> > 
> > Also currently when a user is reported deleted by AMO we set `AMO_User__c` to `False`, do we still need this behavior?
> 
> Hi @mozbrandon. Do you want to answer the above so we move 2/4 requests fwd? Thanks!

Yes. Please continue passing this data as it assists with marketing segmentation.

**Comment by mozbrandon** [comment]
> CRM team to add in field - FxA_Primary_Email__c to capture email address changes via the FxA feed. Work tracked here: #532

`FxA_Primary_Email__c` added to Advo.

**Comment by pmac** [comment]
> Also currently when a user is reported deleted by AMO we set AMO_User__c to False, do we still need this behavior?

In the meeting we thought that the `AMO_User__c` should remain `True` when the account is deleted indicating that they'd once been an AMO user, and the new `AMO_Account_Deleted__c` should be set to `True`.

Also @mozbrandon we still need to know what kind of fields the `AMO_Recommended__c` and `AMO_Account_Deleted__c` are.

**Comment by mozbrandon** [comment]
> Also @mozbrandon we still need to know what kind of fields the `AMO_Recommended__c` and `AMO_Account_Deleted__c` are.

The field types are referenced in the top comment in the field mapping document.

`AMO_Recommended__c` checkbox
`AMO_Account_Deleted__c` checkbox

**Comment by pmac** [comment]
And "checkbox" means boolean? There seems to be no consistency is why we're asking. e.g. `Dev_Disabled__c` on the Addon object has to get "Yes" or "No", but others we can just send `True` or `False`. I assume you'd have said something like "choices" or "picklist" if it was a "Yes" or "No" situation?

**Comment by mozbrandon** [comment]
I'd have to check why `Dev_Disabled__c` has a datatype of "picklist." If it's just to store either a string of "Yes" or "No" then we weren't following best practices and should have used a checkbox field (boolean). 

In the case of `AMO_Recommended__c` and `AMO_Account_Deleted__c` we are using a checkbox field (boolean).

I hope that clears it up and I agree that the lack of consistency is a problem.

**Comment by pmac** [comment]
Definitely. Thanks for the clarification!

**Comment by glogiotatidis** [comment]
Confirmed with @diox that AMO will use `fxa_id` key for FxA ID
