### ISSUE TITLE
Inactivate cc expiring trigger for Subscription services

### ISSUE THREAD

**Issue by desiree-mofo** [mozmeao/basket#524]
As of Monday, May 4, subscription services email confirmations will be sent from the Firefox Accounts team vs. out of Salesforce. The email trigger for credit card expiration date approaching that is triggered by Basket should be inactivated. The other feeds should remain (initial purchase, recurring charge, payment failed, etc). The only trigger that needs to be disabled is the cc expiration date approaching that writes directly to a SFMC Data extension and triggers an email to the customer.

**Comment by pmac** [comment]
@desiree-mofo the SubHub team should stop sending requests with the `event_type` of `customer.source.expiring`. After this those requests will return a 400 error response.

In fact I'm not sure how we'll coordinate this so that there is no loss in email from the basket side. I would think that the best way to go about this is for the SubHub to stop sending the `customer.source.expiring` events to basket at the same time it starts sending email requests to FxA. Thoughts?

**Comment by desiree-mofo** [comment]
I chatted with Stephen Hood (product mgr in IT) and Stew (engineer) and the plan right now it to stop sending the event from Stripe for `customer.source.expiring`

**Comment by pmac** [comment]
Okay cool. So I should still remove this but only sometime after the transition? Is that right?

**Comment by pmac** [comment]
I confirmed with @desiree-mofo that the SubHub team will be disabling the `customer.source.expiring` requests on their end and that we should deploy #525 only after that is done.
