### ISSUE TITLE
Remove API key requirement when unsubscribing from newsletters

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/basket#918]
As part of https://github.com/mozilla/bedrock/issues/11149 we'd like to move as much of the newsletter preference center functionality to the front-end. In order to facilitate, we will need to remove the API key requirement when unsubscribing from newsletters (e.g. in the instance a newsletter is marked as private). 

After some initial discussion, our current thinking is that removing the API key requirement here should be OK, since the worst someone could do is unsubscribe an email address from newsletters they have previously signed up to. In order to do that, they would also need a user's token, which would already give them access to do so anyways via the web site.

**Comment by robhudson** [comment]
The only place I see an API key being passed to basket is here:
https://github.com/mozilla/bedrock/blob/main/bedrock/newsletter/views.py#L429

And following that code through basket client and basket, even that isn't necessary since a token is provided.

**Comment by alexgibson** [comment]
@pmac sounds like this might not be needed for the newsletter management page, unless you know more or we're missing something?

**Comment by pmac** [comment]
IIRC it only becomes an issue if the user is subscribed to a private newsletter. This should be easy to test to be sure. It's why we send an API Key in requests from bedrock.

**Comment by robhudson** [comment]
According to the code, the API key is not required if the user is unsubscribing from a private newsletter. It is required for subscribing to a private newsletter, however.

There is also some logic requiring API keys and double opt-ins (email validation). An API key is required to bypass the email validation it seems. But we aren't trying to bypass this via bedrock, as far as I know.

So I believe there is nothing really to do here in this issue since unsubscribing does not require API keys.

**Comment by alexgibson** [comment]
>According to the code, the API key is not required if the user is unsubscribing from a private newsletter. It is required for subscribing to a private newsletter, however.

Is there a possibility that an API key could be required when POST'ing to https://basket.readthedocs.io/newsletter_api.html#news-user, if it contains a private newsletter ID? Or is that OK since we're providing a token?

**Comment by robhudson** [comment]
Yes, it does currently require an API key for POST'ing to `/news/user/` if it contains a private newsletter ID...

After a few layers of code logic the execution will land here with the `api_call_type` of `SET`:
https://github.com/mozmeao/basket/blob/master/basket/news/views.py#L894

The `is_authorized` is what checks for either a valid API key or a OAuth token:
https://github.com/mozmeao/basket/blob/master/basket/news/utils.py#L118

**Comment by alexgibson** [comment]
OK, so if I'm following correctly then the front-end would encounter an error if:

1 `newsletters="some-private-newsletter,some-public-newsletter"`.
2. User un-checks `some-public-newsletter` as they want to unsubscribe from the public newsletter.
3. We then POST to `/news/user/` with `newsletters="some-private-newsletter"`.

At this point the POST would fail, because the user wants to remain subscribed to `some-private-newsletter`?

If that's right, would it be possible to make it so we don't fail as long as they are _already_ subscribed to `some-private-newsletter`? This could make it so it's still impossible to subscribe to a private newsletter without an API key, whilst still allowing users to update their preferences for other newsletters.

If not, then we might need to look at other solutions.

**Comment by robhudson** [comment]
To accomplish this we'd need to know the list of currently subscribed to newsletters and do some comparison based on the action being requested. Turns out, there is [code that does this](https://github.com/mozmeao/basket/blob/master/basket/news/utils.py#L572) already. But, it isn't wired into the basket views and only kicks in at the background task level before sending request to CTMS. But this should be able to be wired up to the view to do the checking before kicking back a response about missing API keys.

**Comment by alexgibson** [comment]
Great, thanks for all your investigating @robhudson!
