### ISSUE TITLE
Signup form

### ISSUE THREAD

**Issue by tbrlpld** [mozmeao/basket#926]
It would be great if there was a signup form hosted by basket that can serve as a fallback. E.g. on https://foundation.mozilla.org we use a React component to signup to newsletters. So this won't be available until JS is loaded and run. It would be amazing if we could have a link to a signup page on the Basket service as a fallback until JS is ready. Of course, we can add that on our side too, but this might be a problem that other projects using Basket also have and having that from on the service would solve it for all projects.

**Comment by pmac** [comment]
We've considered that in the past, but keeping basket as just an API service seemed the most prudent since there isn't a good way to get people who end up on the form back to where they came from. Not to mention it would likely feel like a scam (or should) if the look and feel and branding of the site suddenly changed just for a newsletter form. 

Thanks for the suggestion though.
